### ISSUE TITLE
Add a way to overwrite the resource path

### ISSUE THREAD

**Issue by TheNeikos** [charlieridley/emu#27]
Right now I am defining my model like this:

```
Ammonia.User = Emu.Model.extend({
etc...
```

Then when I try to fetch the model with id 1 it tries to fetch `user/1`, using rails this should be `users/1`.
Which means that I have to override the resource path.

Right now I can do it on the server but being able to do it clientside feels cleaner in my opinion.

**Comment by charlieridley** [comment]
Could either add pluralizing in the serializer like I think ember-data does, or create an override for the resource name. Either way, I agree this should be client configurable

**Comment by charlesdemers** [comment]
@Com2040 If this can help you until it’s built-in, I made this for my project:

``` javascript
App.Store = Emu.Store.extend({
  plurals: {
    person: 'people'
  },

  adapter: Emu.RestAdapter.extend({

    serializer: Emu.UnderscoreSerializer.extend({
      _pluralize: function(type) {
        return (App.Store.plurals && App.Store.plurals[type]) || type + 's';
      },

      serializeTypeName: function(type) {
        var typeString = type.toString(),
          parts = typeString.split('.'),
          name = parts[parts.length - 1];
        return this._pluralize(name.replace(/([A-Z])/g, '_$1').toLowerCase().slice(1));
      }
    })
  })
});
```

**Comment by TheNeikos** [comment]
By looking at this I see two solutions: You put the value on the model; with the way the current serializer works this means you will have to do `reopenClass` and set it there. ead2a0c is a way to do it. It isn't pretty though.

Or you can use the way @charlesdemers has suggested. With special paths added to the store. This has the added benefit of it being all in one place.

Oh and excuse me if I am approaching this the wrong way, I am still a bit new to Ember and Github as a whole.

**Comment by charlieridley** [comment]
How about configuring the adapter like this?

```
Emu.RestAdapter.configure("App.Customer", {
  resourceName: "customers"
});
```

**Comment by TheNeikos** [comment]
I guess that is a new method? ( I cannot seem to find it in the Ember Docs nor the source. )

But either way, that is also a way to do it and it would keep the configuration close to the model. 

So something like:

```
App.User  = Emu.Model.extend()

Emu.RestAdapter.configure("App.User, {
  resourceName: "customers"
});
```

It does seem to be a working option, but in my opinion that is a lot of code to tell something simple.

**Comment by charlieridley** [comment]
Yeah I meant that as a suggestion of how the configuration could be implemented. I modifying the underscore serializer to incorporate @charlesdemers pluralization solution is best because that'll support people using a rails back end. I'll do that when I get a chance, or charles if you want to submit a pull request

**Comment by charlieridley** [comment]
Could use this for pluralization?

https://github.com/stefanpenner/ember-inflector/blob/master/packages/ember-inflector/lib/system/inflections.js

**Comment by jonnii** [comment]
how about something like this:

```
App.Model.reopenClass(function(){
    collectionUrl: function(){ return "/orders"; },
    instanceUrl: function(instance){ return "/order/" + instance.get('id"); } 
});
```

**Comment by charlesdemers** [comment]
@jonnii I think it may be good if you want to really override everything, but having a strong convention like only pluralizing model names is better IMO.

**Comment by jonnii** [comment]
I think the default should be pluralization, but it'd be nice to override depending on the instance too.

**Comment by charlieridley** [comment]
Pluralization in the UnderscoreSerializer, thanks @charlesdemers 

https://github.com/charlieridley/emu/commit/b1706b41848442e9f25821866bec7bef06298212

**Comment by TheNeikos** [comment]
Perfect! Thanks
