### ISSUE TITLE
Deserialized value is not set if it is falsy

### ISSUE THREAD

**Issue by niklas** [charlieridley/emu#29]
Hey, I was playing around with emu a bit and found the following bug: If an updated value is serialized to a falsy entity (for example the number 0), it won't be set on the model.

Use case: I have added an attribute serializer for 'number' (same as for string) for a field representing progress, which is 0 at the start.

Is there a specific reason for the postfix `if`?

https://github.com/charlieridley/emu/blob/master/src/emu/serializer/serializer.js.coffee#L57

**Comment by charlieridley** [comment]
Fixed this issue which would occur when value is 0. The check is there for allowing the serializer to deserialize partial json objects for updates from the pushdataadapter. The serializer code isn't that clear so I need to clean it up a bit really but you issue should be fixed for now.
