### ISSUE TITLE
isNew model state

### ISSUE THREAD

**Issue by hathvi** [charlieridley/emu#35]
It would be nice if models had an isNew state. Right now I'm just using an isNew computed property that observes the primary key attribute for the model on the models that need it.

**Comment by charlieridley** [comment]
I thinks so too, I'll implement that

**Comment by charlieridley** [comment]
There's now an isSaved flag which will be false on a new model. It will be true after loading and saving a model

**Comment by hathvi** [comment]
Thanks!
